spring:
  application:
    name: eureka
  cloud:
    config:
      fail-fast: true
      uri: ${CONFIG_REPO_HOST:http://localhost:8888}
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000